INSERT INTO classes VALUES ('CIS 115', 'Introduction to computing science', NULL);
INSERT INTO classes VALUES ('CIS 200', 'Fundamentals of Software Design and Implementation', 'CIS 115');
INSERT INTO classes VALUES ('CIS 300', 'Data and Program Structures', 'CIS 200');
INSERT INTO classes VALUES ('CIS 301', 'Logical Foundations of Programming', 'CIS 200');
INSERT INTO classes VALUES ('CIS 308', 'C/C++ Programming Laboratory', 'CIS 300');
INSERT INTO classes VALUES ('CIS 415', 'Computers and Society', NULL);
INSERT INTO classes VALUES ('CIS 450', 'Computer Architecture and Operations', 'CIS 308');
INSERT INTO classes VALUES ('CIS 501', 'Software Architecture and Design', 'CIS 301');
INSERT INTO classes VALUES ('CIS 560', 'Database System Concepts', NULL);
INSERT INTO classes VALUES ('CIS 575', 'Introduction to Algorithm Analysis', 'CIS 308');
INSERT INTO classes VALUES ('CIS 505', 'Introduction to Programming Languages', NULL);
INSERT INTO classes VALUES ('CIS 520', 'Operating Systems I', NULL);
INSERT INTO classes VALUES ('MATH 220', 'Analytic Geometry and Calculus I', NULL);
INSERT INTO classes VALUES ('MATH 221', 'Analytic Geometry and Calculus II', 'MATH 220');
INSERT INTO classes VALUES ('MATH 510', 'Discrete Mathematics', 'MATH 221');
INSERT INTO classes VALUES ('MATH 551', 'Applied Matrix Theory', NULL);
INSERT INTO classes VALUES ('STAT 510', 'Introductory Probability and Statistics I', NULL);
INSERT INTO classes VALUES ('ENGL 100', 'Expository Writing I', NULL);
INSERT INTO classes VALUES ('ENGL 200', 'Expository Writing II', 'ENGL 100');
INSERT INTO classes VALUES ('ENGL 516', 'Written Communication for the Sciences', 'ENGL 200');
